export { HomePage } from "./home/home";
export { CarritoPage } from "./carrito/carrito";
export { CategoriasPage } from "./categorias/categorias";
export { LoginPage } from "./login/login";
export { OrdenesPage } from "./ordenes/ordenes";
export { OrdenesDetallePage } from "./ordenes-detalle/ordenes-detalle";
export { PorCategoriasPage } from "./por-categorias/por-categorias";
export { TabsPage } from "./tabs/tabs";
export { ProductoPage } from "./producto/producto";
export { BusquedaPage } from "./busqueda/busqueda";
export { Introduccion } from "./introduccion/introduccion";
export { RegistrarsePage } from "./registrarse/registrarse";
export { AboutPage } from "./about/about";
export  {ErrorRedPage} from "./error-red/error-red";